#!/bin/sh
npm i --save-dev react-app-rewired assert stream-http url buffer process crypto-browserify stream-browserify https-browserify os-browserify path-browserify vm-browserify

cp -rf config-overrides.js ../../

sed -i 's+react-scripts start+react-app-rewired start+g' ../../package.json
sed -i 's+react-scripts build+react-app-rewired build+g' ../../package.json
sed -i 's+react-scripts test+react-app-rewired test+g' ../../package.json